window.PHOTO_CORRIDOR_RECORDS = [
  {
    "id": "real-valley-summer",
    "category": "real",
    "src": "assets/images/photo-corridor/real-valley-summer.jpg",
    "width": 1280,
    "height": 720,
    "alt": "A still mountain lake reflecting a bright summer sky",
    "title": "Valley, Summer",
    "date": "2026.07",
    "description": "A clear afternoon held in the personal collection.",
    "frame": "wood",
    "size": "landscape",
    "tilt": -0.45
  },
  {
    "id": "archive-entrance-1998",
    "category": "archive",
    "src": "assets/images/photo-corridor/archive-entrance-1998.jpg",
    "width": 1200,
    "height": 800,
    "alt": "The modest concrete entrance of an archive building with wooden doors",
    "title": "East Entrance",
    "date": "1998.04",
    "description": "The east entrance before the second interior renovation.",
    "frame": "metal",
    "size": "portrait",
    "tilt": 0.55
  },
  {
    "id": "real-valley-blue-hour",
    "category": "real",
    "src": "assets/images/photo-corridor/real-valley-blue-hour.jpg",
    "width": 1280,
    "height": 720,
    "alt": "A mountain lake under a dark blue overcast sky",
    "title": "Blue Hour",
    "date": "2026.07",
    "description": "The same valley after the light left the water.",
    "frame": "brass",
    "size": "landscape",
    "tilt": 0.35
  },
  {
    "id": "anomaly-staff-2004",
    "category": "anomalies",
    "src": "assets/images/photo-corridor/anomaly-staff-2004.jpg",
    "width": 1200,
    "height": 800,
    "alt": "An archive staff group portrait with one seated person facing away from the camera",
    "title": "Staff Assembly",
    "date": "2004.11",
    "description": "Personnel roster: ten entries. Photograph: eleven subjects.",
    "frame": "wood",
    "size": "landscape",
    "tilt": -0.2
  },
  {
    "id": "archive-workstation-2002",
    "category": "archive",
    "src": "assets/images/photo-corridor/archive-workstation-2002.jpg",
    "width": 1200,
    "height": 800,
    "alt": "A beige CRT archive workstation on a wooden desk",
    "title": "Index Terminal 03",
    "date": "2002.09",
    "description": "Equipment record from the first digitization room.",
    "frame": "metal",
    "size": "square",
    "tilt": 0.7
  },
  {
    "id": "archive-hall-2026",
    "category": "archive",
    "src": "assets/images/photo-corridor/archive-hall-2026.jpg",
    "width": 1280,
    "height": 720,
    "alt": "The Archive Hall with a CRT computer on a large wooden desk",
    "title": "Archive Hall",
    "date": "2026.06",
    "description": "Reference photograph taken before public access was restored.",
    "frame": "brass",
    "size": "portrait",
    "tilt": -0.75
  }
];
